eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-API/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-API/order/bookOrder    

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teejay?verifyServerCertificate=false&useSSL=true&requireSSL=true
    username: root
    password: Admin1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
